db.City.insert({_id:1, city:"Ballard", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"WA ", stateProvinceName:"Washington"});
db.City.insert({_id:2, city:"Barstow", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"CA ", stateProvinceName:"California"});
db.City.insert({_id:3, city:"Basingstoke Hants", countryRegionCode:"GB ", countryRegionName:"United Kingdom", stateProvinceCode:"ENG", stateProvinceName:"England"});
db.City.insert({_id:4, city:"Baytown", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"TX ", stateProvinceName:"Texas"});
db.City.insert({_id:5, city:"Beaverton", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"OR ", stateProvinceName:"Oregon"});
db.City.insert({_id:6, city:"Bell Gardens", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"CA ", stateProvinceName:"California"});
db.City.insert({_id:7, city:"Bellevue", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"WA ", stateProvinceName:"Washington"});
db.City.insert({_id:8, city:"Bellflower", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"CA ", stateProvinceName:"California"});
db.City.insert({_id:9, city:"Bellingham", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"WA ", stateProvinceName:"Washington"});
db.City.insert({_id:10, city:"Bendigo", countryRegionCode:"AU ", countryRegionName:"Australia", stateProvinceCode:"VIC", stateProvinceName:"Victoria"});
db.City.insert({_id:11, city:"Berkeley", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"CA ", stateProvinceName:"California"});
db.City.insert({_id:12, city:"Berks", countryRegionCode:"GB ", countryRegionName:"United Kingdom", stateProvinceCode:"ENG", stateProvinceName:"England"});
db.City.insert({_id:13, city:"Berkshire", countryRegionCode:"GB ", countryRegionName:"United Kingdom", stateProvinceCode:"ENG", stateProvinceName:"England"});
db.City.insert({_id:14, city:"Berlin", countryRegionCode:"DE ", countryRegionName:"Germany", stateProvinceCode:"HE ", stateProvinceName:"Hessen"});
db.City.insert({_id:15, city:"Berlin", countryRegionCode:"DE ", countryRegionName:"Germany", stateProvinceCode:"HH ", stateProvinceName:"Hamburg"});
db.City.insert({_id:16, city:"Berlin", countryRegionCode:"DE ", countryRegionName:"Germany", stateProvinceCode:"NW ", stateProvinceName:"Nordrhein-Westfalen"});
db.City.insert({_id:17, city:"Berlin", countryRegionCode:"DE ", countryRegionName:"Germany", stateProvinceCode:"SL ", stateProvinceName:"Saarland"});
db.City.insert({_id:18, city:"Beverly Hills", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"CA ", stateProvinceName:"California"});
db.City.insert({_id:19, city:"Billericay", countryRegionCode:"GB ", countryRegionName:"United Kingdom", stateProvinceCode:"ENG", stateProvinceName:"England"});
db.City.insert({_id:20, city:"Billings", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"MT ", stateProvinceName:"Montana"});
db.City.insert({_id:21, city:"Biloxi", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"MS ", stateProvinceName:"Mississippi"});
db.City.insert({_id:22, city:"Birmingham", countryRegionCode:"GB ", countryRegionName:"United Kingdom", stateProvinceCode:"ENG", stateProvinceName:"England"});
db.City.insert({_id:23, city:"Birmingham", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"AL ", stateProvinceName:"Alabama"});
db.City.insert({_id:24, city:"Bluffton", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"SC ", stateProvinceName:"South Carolina"});
db.City.insert({_id:25, city:"Bobigny", countryRegionCode:"FR ", countryRegionName:"France", stateProvinceCode:"93 ", stateProvinceName:"Seine Saint Denis"});
db.City.insert({_id:26, city:"Bonn", countryRegionCode:"DE ", countryRegionName:"Germany", stateProvinceCode:"HH ", stateProvinceName:"Hamburg"});
db.City.insert({_id:27, city:"Bonn", countryRegionCode:"DE ", countryRegionName:"Germany", stateProvinceCode:"NW ", stateProvinceName:"Nordrhein-Westfalen"});
db.City.insert({_id:28, city:"Bothell", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"WA ", stateProvinceName:"Washington"});
db.City.insert({_id:29, city:"Bottrop", countryRegionCode:"DE ", countryRegionName:"Germany", stateProvinceCode:"NW ", stateProvinceName:"Nordrhein-Westfalen"});
db.City.insert({_id:30, city:"Boulogne-Billancourt", countryRegionCode:"FR ", countryRegionName:"France", stateProvinceCode:"92 ", stateProvinceName:"Hauts de Seine"});
db.City.insert({_id:31, city:"Boulogne-sur-Mer", countryRegionCode:"FR ", countryRegionName:"France", stateProvinceCode:"62 ", stateProvinceName:"Pas de Calais"});
db.City.insert({_id:32, city:"Bountiful", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"UT ", stateProvinceName:"Utah"});
db.City.insert({_id:33, city:"Bracknell", countryRegionCode:"GB ", countryRegionName:"United Kingdom", stateProvinceCode:"ENG", stateProvinceName:"England"});
db.City.insert({_id:34, city:"Bradenton", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"FL ", stateProvinceName:"Florida"});
db.City.insert({_id:35, city:"Braintree", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"MA ", stateProvinceName:"Massachusetts"});
db.City.insert({_id:36, city:"Branch", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"MN ", stateProvinceName:"Minnesota"});
db.City.insert({_id:37, city:"Branson", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"MO ", stateProvinceName:"Missouri"});
db.City.insert({_id:38, city:"Braunschweig", countryRegionCode:"DE ", countryRegionName:"Germany", stateProvinceCode:"NW ", stateProvinceName:"Nordrhein-Westfalen"});
db.City.insert({_id:39, city:"Bremerton", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"WA ", stateProvinceName:"Washington"});
db.City.insert({_id:40, city:"Brisbane", countryRegionCode:"AU ", countryRegionName:"Australia", stateProvinceCode:"QLD", stateProvinceName:"Queensland"});
db.City.insert({_id:41, city:"Burbank", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"CA ", stateProvinceName:"California"});
db.City.insert({_id:42, city:"Burbank", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"OH ", stateProvinceName:"Ohio"});
db.City.insert({_id:43, city:"Burien", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"WA ", stateProvinceName:"Washington"});
db.City.insert({_id:44, city:"Burlingame", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"CA ", stateProvinceName:"California"});
db.City.insert({_id:45, city:"Burnaby", countryRegionCode:"CA ", countryRegionName:"Canada", stateProvinceCode:"BC ", stateProvinceName:"British Columbia"});
db.City.insert({_id:46, city:"Bury", countryRegionCode:"GB ", countryRegionName:"United Kingdom", stateProvinceCode:"ENG", stateProvinceName:"England"});
db.City.insert({_id:47, city:"Byron", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"GA ", stateProvinceName:"Georgia"});
db.City.insert({_id:48, city:"Calgary", countryRegionCode:"CA ", countryRegionName:"Canada", stateProvinceCode:"AB ", stateProvinceName:"Alberta"});
db.City.insert({_id:49, city:"Caloundra", countryRegionCode:"AU ", countryRegionName:"Australia", stateProvinceCode:"QLD", stateProvinceName:"Queensland"});
db.City.insert({_id:50, city:"Camarillo", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"CA ", stateProvinceName:"California"});
db.City.insert({_id:51, city:"Cambridge", countryRegionCode:"GB ", countryRegionName:"United Kingdom", stateProvinceCode:"ENG", stateProvinceName:"England"});
db.City.insert({_id:52, city:"Campbellsville", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"KY ", stateProvinceName:"Kentucky"});
db.City.insert({_id:53, city:"Canoga Park", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"CA ", stateProvinceName:"California"});
db.City.insert({_id:54, city:"Carol Stream", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"IL ", stateProvinceName:"Illinois"});
db.City.insert({_id:55, city:"Carrollton", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"TX ", stateProvinceName:"Texas"});
db.City.insert({_id:56, city:"Carson", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"CA ", stateProvinceName:"California"});
db.City.insert({_id:57, city:"Casper", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"WY ", stateProvinceName:"Wyoming"});
db.City.insert({_id:58, city:"Cedar City", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"UT ", stateProvinceName:"Utah"});
db.City.insert({_id:59, city:"Cedar Park", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"TX ", stateProvinceName:"Texas"});
db.City.insert({_id:60, city:"Central Valley", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"NY ", stateProvinceName:"New York"});
db.City.insert({_id:61, city:"Cergy", countryRegionCode:"FR ", countryRegionName:"France", stateProvinceCode:"95 ", stateProvinceName:"Val d'Oise"});
db.City.insert({_id:62, city:"Cerritos", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"CA ", stateProvinceName:"California"});
db.City.insert({_id:63, city:"Chalk Riber", countryRegionCode:"CA ", countryRegionName:"Canada", stateProvinceCode:"ON ", stateProvinceName:"Ontario"});
db.City.insert({_id:64, city:"Chandler", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"AZ ", stateProvinceName:"Arizona"});
db.City.insert({_id:65, city:"Chantilly", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"VA ", stateProvinceName:"Virginia"});
db.City.insert({_id:66, city:"Charlotte", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"NC ", stateProvinceName:"North Carolina"});
db.City.insert({_id:67, city:"Chatou", countryRegionCode:"FR ", countryRegionName:"France", stateProvinceCode:"78 ", stateProvinceName:"Yveline"});
db.City.insert({_id:68, city:"Cheektowaga", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"NY ", stateProvinceName:"New York"});
db.City.insert({_id:69, city:"Chehalis", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"WA ", stateProvinceName:"Washington"});
db.City.insert({_id:70, city:"Cheltenham", countryRegionCode:"GB ", countryRegionName:"United Kingdom", stateProvinceCode:"ENG", stateProvinceName:"England"});
db.City.insert({_id:71, city:"Cheyenne", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"WY ", stateProvinceName:"Wyoming"});
db.City.insert({_id:72, city:"Chicago", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"IL ", stateProvinceName:"Illinois"});
db.City.insert({_id:73, city:"Chula Vista", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"CA ", stateProvinceName:"California"});
db.City.insert({_id:74, city:"Cincinnati", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"OH ", stateProvinceName:"Ohio"});
db.City.insert({_id:75, city:"Citrus Heights", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"CA ", stateProvinceName:"California"});
db.City.insert({_id:76, city:"City Of Commerce", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"CA ", stateProvinceName:"California"});
db.City.insert({_id:77, city:"Clackamas", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"OR ", stateProvinceName:"Oregon"});
db.City.insert({_id:78, city:"Clarkston", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"GA ", stateProvinceName:"Georgia"});
db.City.insert({_id:79, city:"Clay", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"NY ", stateProvinceName:"New York"});
db.City.insert({_id:80, city:"Clearwater", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"FL ", stateProvinceName:"Florida"});
db.City.insert({_id:81, city:"Cliffside", countryRegionCode:"CA ", countryRegionName:"Canada", stateProvinceCode:"BC ", stateProvinceName:"British Columbia"});
db.City.insert({_id:82, city:"Cloverdale", countryRegionCode:"AU ", countryRegionName:"Australia", stateProvinceCode:"SA ", stateProvinceName:"South Australia"});
db.City.insert({_id:83, city:"Coffs Harbour", countryRegionCode:"AU ", countryRegionName:"Australia", stateProvinceCode:"NSW", stateProvinceName:"New South Wales"});
db.City.insert({_id:84, city:"College Station", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"TX ", stateProvinceName:"Texas"});
db.City.insert({_id:85, city:"Colma", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"CA ", stateProvinceName:"California"});
db.City.insert({_id:86, city:"Colombes", countryRegionCode:"FR ", countryRegionName:"France", stateProvinceCode:"92 ", stateProvinceName:"Hauts de Seine"});
db.City.insert({_id:87, city:"Colomiers", countryRegionCode:"FR ", countryRegionName:"France", stateProvinceCode:"31 ", stateProvinceName:"Garonne (Haute)"});
db.City.insert({_id:88, city:"Columbus", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"GA ", stateProvinceName:"Georgia"});
db.City.insert({_id:89, city:"Columbus", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"OH ", stateProvinceName:"Ohio"});
db.City.insert({_id:90, city:"Concord", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"CA ", stateProvinceName:"California"});
db.City.insert({_id:91, city:"Coronado", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"CA ", stateProvinceName:"California"});
db.City.insert({_id:92, city:"Corvallis", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"OR ", stateProvinceName:"Oregon"});
db.City.insert({_id:93, city:"Courbevoie", countryRegionCode:"FR ", countryRegionName:"France", stateProvinceCode:"92 ", stateProvinceName:"Hauts de Seine"});
db.City.insert({_id:94, city:"Cranbourne", countryRegionCode:"AU ", countryRegionName:"Australia", stateProvinceCode:"VIC", stateProvinceName:"Victoria"});
db.City.insert({_id:95, city:"Croix", countryRegionCode:"FR ", countryRegionName:"France", stateProvinceCode:"59 ", stateProvinceName:"Nord"});
db.City.insert({_id:96, city:"Daly City", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"CA ", stateProvinceName:"California"});
db.City.insert({_id:97, city:"Darlinghurst", countryRegionCode:"AU ", countryRegionName:"Australia", stateProvinceCode:"NSW", stateProvinceName:"New South Wales"});
db.City.insert({_id:98, city:"Darmstadt", countryRegionCode:"DE ", countryRegionName:"Germany", stateProvinceCode:"HE ", stateProvinceName:"Hessen"});
db.City.insert({_id:99, city:"Downey", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"CA ", stateProvinceName:"California"});
db.City.insert({_id:100, city:"Drancy", countryRegionCode:"FR ", countryRegionName:"France", stateProvinceCode:"93 ", stateProvinceName:"Seine Saint Denis"});
db.City.insert({_id:101, city:"Dresden", countryRegionCode:"DE ", countryRegionName:"Germany", stateProvinceCode:"HE ", stateProvinceName:"Hessen"});
db.City.insert({_id:102, city:"Duesseldorf", countryRegionCode:"DE ", countryRegionName:"Germany", stateProvinceCode:"HE ", stateProvinceName:"Hessen"});
db.City.insert({_id:103, city:"Dunkerque", countryRegionCode:"FR ", countryRegionName:"France", stateProvinceCode:"59 ", stateProvinceName:"Nord"});
db.City.insert({_id:104, city:"East Brisbane", countryRegionCode:"AU ", countryRegionName:"Australia", stateProvinceCode:"QLD", stateProvinceName:"Queensland"});
db.City.insert({_id:105, city:"Edmonds", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"WA ", stateProvinceName:"Washington"});
db.City.insert({_id:106, city:"Eilenburg", countryRegionCode:"DE ", countryRegionName:"Germany", stateProvinceCode:"BB ", stateProvinceName:"Brandenburg"});
db.City.insert({_id:107, city:"El Cajon", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"CA ", stateProvinceName:"California"});
db.City.insert({_id:108, city:"Erlangen", countryRegionCode:"DE ", countryRegionName:"Germany", stateProvinceCode:"BY ", stateProvinceName:"Bayern"});
db.City.insert({_id:109, city:"Esher-Molesey", countryRegionCode:"GB ", countryRegionName:"United Kingdom", stateProvinceCode:"ENG", stateProvinceName:"England"});
db.City.insert({_id:110, city:"Essen", countryRegionCode:"DE ", countryRegionName:"Germany", stateProvinceCode:"HH ", stateProvinceName:"Hamburg"});
db.City.insert({_id:111, city:"Everett", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"WA ", stateProvinceName:"Washington"});
db.City.insert({_id:112, city:"Findon", countryRegionCode:"AU ", countryRegionName:"Australia", stateProvinceCode:"SA ", stateProvinceName:"South Australia"});
db.City.insert({_id:113, city:"Frankfurt", countryRegionCode:"DE ", countryRegionName:"Germany", stateProvinceCode:"BY ", stateProvinceName:"Bayern"});
db.City.insert({_id:114, city:"Frankfurt", countryRegionCode:"DE ", countryRegionName:"Germany", stateProvinceCode:"HE ", stateProvinceName:"Hessen"});
db.City.insert({_id:115, city:"Frankfurt am Main", countryRegionCode:"DE ", countryRegionName:"Germany", stateProvinceCode:"HH ", stateProvinceName:"Hamburg"});
db.City.insert({_id:116, city:"Frankfurt am Main", countryRegionCode:"DE ", countryRegionName:"Germany", stateProvinceCode:"SL ", stateProvinceName:"Saarland"});
db.City.insert({_id:117, city:"Fremont", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"CA ", stateProvinceName:"California"});
db.City.insert({_id:118, city:"Gateshead", countryRegionCode:"GB ", countryRegionName:"United Kingdom", stateProvinceCode:"ENG", stateProvinceName:"England"});
db.City.insert({_id:119, city:"Geelong", countryRegionCode:"AU ", countryRegionName:"Australia", stateProvinceCode:"VIC", stateProvinceName:"Victoria"});
db.City.insert({_id:120, city:"Glendale", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"CA ", stateProvinceName:"California"});
db.City.insert({_id:121, city:"Gloucestershire", countryRegionCode:"GB ", countryRegionName:"United Kingdom", stateProvinceCode:"ENG", stateProvinceName:"England"});
db.City.insert({_id:122, city:"Gold Coast", countryRegionCode:"AU ", countryRegionName:"Australia", stateProvinceCode:"QLD", stateProvinceName:"Queensland"});
db.City.insert({_id:123, city:"Goulburn", countryRegionCode:"AU ", countryRegionName:"Australia", stateProvinceCode:"NSW", stateProvinceName:"New South Wales"});
db.City.insert({_id:124, city:"Grevenbroich", countryRegionCode:"DE ", countryRegionName:"Germany", stateProvinceCode:"BY ", stateProvinceName:"Bayern"});
db.City.insert({_id:125, city:"Grossmont", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"CA ", stateProvinceName:"California"});
db.City.insert({_id:126, city:"Hamburg", countryRegionCode:"DE ", countryRegionName:"Germany", stateProvinceCode:"HE ", stateProvinceName:"Hessen"});
db.City.insert({_id:127, city:"Hamburg", countryRegionCode:"DE ", countryRegionName:"Germany", stateProvinceCode:"HH ", stateProvinceName:"Hamburg"});
db.City.insert({_id:128, city:"Haney", countryRegionCode:"CA ", countryRegionName:"Canada", stateProvinceCode:"BC ", stateProvinceName:"British Columbia"});
db.City.insert({_id:129, city:"Hannover", countryRegionCode:"DE ", countryRegionName:"Germany", stateProvinceCode:"NW ", stateProvinceName:"Nordrhein-Westfalen"});
db.City.insert({_id:130, city:"Hawthorne", countryRegionCode:"AU ", countryRegionName:"Australia", stateProvinceCode:"QLD", stateProvinceName:"Queensland"});
db.City.insert({_id:131, city:"Hervey Bay", countryRegionCode:"AU ", countryRegionName:"Australia", stateProvinceCode:"QLD", stateProvinceName:"Queensland"});
db.City.insert({_id:132, city:"High Wycombe", countryRegionCode:"GB ", countryRegionName:"United Kingdom", stateProvinceCode:"ENG", stateProvinceName:"England"});
db.City.insert({_id:133, city:"Hobart", countryRegionCode:"AU ", countryRegionName:"Australia", stateProvinceCode:"TAS", stateProvinceName:"Tasmania"});
db.City.insert({_id:134, city:"Hof", countryRegionCode:"DE ", countryRegionName:"Germany", stateProvinceCode:"BY ", stateProvinceName:"Bayern"});
db.City.insert({_id:135, city:"Imperial Beach", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"CA ", stateProvinceName:"California"});
db.City.insert({_id:136, city:"Ingolstadt", countryRegionCode:"DE ", countryRegionName:"Germany", stateProvinceCode:"BY ", stateProvinceName:"Bayern"});
db.City.insert({_id:137, city:"Issaquah", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"WA ", stateProvinceName:"Washington"});
db.City.insert({_id:138, city:"Kassel", countryRegionCode:"DE ", countryRegionName:"Germany", stateProvinceCode:"HE ", stateProvinceName:"Hessen"});
db.City.insert({_id:139, city:"Kiel", countryRegionCode:"DE ", countryRegionName:"Germany", stateProvinceCode:"SL ", stateProvinceName:"Saarland"});
db.City.insert({_id:140, city:"Kirkby", countryRegionCode:"GB ", countryRegionName:"United Kingdom", stateProvinceCode:"ENG", stateProvinceName:"England"});
db.City.insert({_id:141, city:"Kirkland", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"WA ", stateProvinceName:"Washington"});
db.City.insert({_id:142, city:"La Jolla", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"CA ", stateProvinceName:"California"});
db.City.insert({_id:143, city:"Lake Oswego", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"OR ", stateProvinceName:"Oregon"});
db.City.insert({_id:144, city:"Lakewood", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"CA ", stateProvinceName:"California"});
db.City.insert({_id:145, city:"Lancaster", countryRegionCode:"GB ", countryRegionName:"United Kingdom", stateProvinceCode:"ENG", stateProvinceName:"England"});
db.City.insert({_id:146, city:"Lane Cove", countryRegionCode:"AU ", countryRegionName:"Australia", stateProvinceCode:"NSW", stateProvinceName:"New South Wales"});
db.City.insert({_id:147, city:"Langford", countryRegionCode:"CA ", countryRegionName:"Canada", stateProvinceCode:"BC ", stateProvinceName:"British Columbia"});
db.City.insert({_id:148, city:"Langley", countryRegionCode:"CA ", countryRegionName:"Canada", stateProvinceCode:"BC ", stateProvinceName:"British Columbia"});
db.City.insert({_id:149, city:"Lavender Bay", countryRegionCode:"AU ", countryRegionName:"Australia", stateProvinceCode:"NSW", stateProvinceName:"New South Wales"});
db.City.insert({_id:150, city:"Lebanon", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"OR ", stateProvinceName:"Oregon"});
db.City.insert({_id:151, city:"Leeds", countryRegionCode:"GB ", countryRegionName:"United Kingdom", stateProvinceCode:"ENG", stateProvinceName:"England"});
db.City.insert({_id:152, city:"Leipzig", countryRegionCode:"DE ", countryRegionName:"Germany", stateProvinceCode:"NW ", stateProvinceName:"Nordrhein-Westfalen"});
db.City.insert({_id:153, city:"Lemon Grove", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"CA ", stateProvinceName:"California"});
db.City.insert({_id:154, city:"Les Ulis", countryRegionCode:"FR ", countryRegionName:"France", stateProvinceCode:"91 ", stateProvinceName:"Essonne"});
db.City.insert({_id:155, city:"Lieusaint", countryRegionCode:"FR ", countryRegionName:"France", stateProvinceCode:"77 ", stateProvinceName:"Seine et Marne"});
db.City.insert({_id:156, city:"Lille", countryRegionCode:"FR ", countryRegionName:"France", stateProvinceCode:"59 ", stateProvinceName:"Nord"});
db.City.insert({_id:157, city:"Lincoln Acres", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"CA ", stateProvinceName:"California"});
db.City.insert({_id:158, city:"Liverpool", countryRegionCode:"GB ", countryRegionName:"United Kingdom", stateProvinceCode:"ENG", stateProvinceName:"England"});
db.City.insert({_id:159, city:"London", countryRegionCode:"GB ", countryRegionName:"United Kingdom", stateProvinceCode:"ENG", stateProvinceName:"England"});
db.City.insert({_id:160, city:"Long Beach", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"CA ", stateProvinceName:"California"});
db.City.insert({_id:161, city:"Los Angeles", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"CA ", stateProvinceName:"California"});
db.City.insert({_id:162, city:"Lynnwood", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"WA ", stateProvinceName:"Washington"});
db.City.insert({_id:163, city:"M?hlheim", countryRegionCode:"DE ", countryRegionName:"Germany", stateProvinceCode:"HH ", stateProvinceName:"Hamburg"});
db.City.insert({_id:164, city:"M?nchen", countryRegionCode:"DE ", countryRegionName:"Germany", stateProvinceCode:"HE ", stateProvinceName:"Hessen"});
db.City.insert({_id:165, city:"M?nchen", countryRegionCode:"DE ", countryRegionName:"Germany", stateProvinceCode:"HH ", stateProvinceName:"Hamburg"});
db.City.insert({_id:166, city:"M?nchen", countryRegionCode:"DE ", countryRegionName:"Germany", stateProvinceCode:"NW ", stateProvinceName:"Nordrhein-Westfalen"});
db.City.insert({_id:167, city:"M?nchen", countryRegionCode:"DE ", countryRegionName:"Germany", stateProvinceCode:"SL ", stateProvinceName:"Saarland"});
db.City.insert({_id:168, city:"M?nster", countryRegionCode:"DE ", countryRegionName:"Germany", stateProvinceCode:"SL ", stateProvinceName:"Saarland"});
db.City.insert({_id:169, city:"Maidenhead", countryRegionCode:"GB ", countryRegionName:"United Kingdom", stateProvinceCode:"ENG", stateProvinceName:"England"});
db.City.insert({_id:170, city:"Malabar", countryRegionCode:"AU ", countryRegionName:"Australia", stateProvinceCode:"NSW", stateProvinceName:"New South Wales"});
db.City.insert({_id:171, city:"Marysville", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"WA ", stateProvinceName:"Washington"});
db.City.insert({_id:172, city:"Matraville", countryRegionCode:"AU ", countryRegionName:"Australia", stateProvinceCode:"NSW", stateProvinceName:"New South Wales"});
db.City.insert({_id:173, city:"Melbourne", countryRegionCode:"AU ", countryRegionName:"Australia", stateProvinceCode:"VIC", stateProvinceName:"Victoria"});
db.City.insert({_id:174, city:"Melton", countryRegionCode:"AU ", countryRegionName:"Australia", stateProvinceCode:"VIC", stateProvinceName:"Victoria"});
db.City.insert({_id:175, city:"Metchosin", countryRegionCode:"CA ", countryRegionName:"Canada", stateProvinceCode:"BC ", stateProvinceName:"British Columbia"});
db.City.insert({_id:176, city:"Metz", countryRegionCode:"FR ", countryRegionName:"France", stateProvinceCode:"57 ", stateProvinceName:"Moselle"});
db.City.insert({_id:177, city:"Mill Valley", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"CA ", stateProvinceName:"California"});
db.City.insert({_id:178, city:"Milsons Point", countryRegionCode:"AU ", countryRegionName:"Australia", stateProvinceCode:"NSW", stateProvinceName:"New South Wales"});
db.City.insert({_id:179, city:"Milton Keynes", countryRegionCode:"GB ", countryRegionName:"United Kingdom", stateProvinceCode:"ENG", stateProvinceName:"England"});
db.City.insert({_id:180, city:"Milwaukie", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"OR ", stateProvinceName:"Oregon"});
db.City.insert({_id:181, city:"Morangis", countryRegionCode:"FR ", countryRegionName:"France", stateProvinceCode:"91 ", stateProvinceName:"Essonne"});
db.City.insert({_id:182, city:"N. Vancouver", countryRegionCode:"CA ", countryRegionName:"Canada", stateProvinceCode:"BC ", stateProvinceName:"British Columbia"});
db.City.insert({_id:183, city:"National City", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"CA ", stateProvinceName:"California"});
db.City.insert({_id:184, city:"Neunkirchen", countryRegionCode:"DE ", countryRegionName:"Germany", stateProvinceCode:"SL ", stateProvinceName:"Saarland"});
db.City.insert({_id:185, city:"Newcastle", countryRegionCode:"AU ", countryRegionName:"Australia", stateProvinceCode:"NSW", stateProvinceName:"New South Wales"});
db.City.insert({_id:186, city:"Newcastle upon Tyne", countryRegionCode:"GB ", countryRegionName:"United Kingdom", stateProvinceCode:"ENG", stateProvinceName:"England"});
db.City.insert({_id:187, city:"Newport Beach", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"CA ", stateProvinceName:"California"});
db.City.insert({_id:188, city:"Newton", countryRegionCode:"CA ", countryRegionName:"Canada", stateProvinceCode:"BC ", stateProvinceName:"British Columbia"});
db.City.insert({_id:189, city:"North Ryde", countryRegionCode:"AU ", countryRegionName:"Australia", stateProvinceCode:"NSW", stateProvinceName:"New South Wales"});
db.City.insert({_id:190, city:"North Sydney", countryRegionCode:"AU ", countryRegionName:"Australia", stateProvinceCode:"NSW", stateProvinceName:"New South Wales"});
db.City.insert({_id:191, city:"Novato", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"CA ", stateProvinceName:"California"});
db.City.insert({_id:192, city:"Oak Bay", countryRegionCode:"CA ", countryRegionName:"Canada", stateProvinceCode:"BC ", stateProvinceName:"British Columbia"});
db.City.insert({_id:193, city:"Oakland", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"CA ", stateProvinceName:"California"});
db.City.insert({_id:194, city:"Offenbach", countryRegionCode:"DE ", countryRegionName:"Germany", stateProvinceCode:"SL ", stateProvinceName:"Saarland"});
db.City.insert({_id:195, city:"Olympia", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"WA ", stateProvinceName:"Washington"});
db.City.insert({_id:196, city:"Oregon City", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"OR ", stateProvinceName:"Oregon"});
db.City.insert({_id:197, city:"Orleans", countryRegionCode:"FR ", countryRegionName:"France", stateProvinceCode:"45 ", stateProvinceName:"Loiret"});
db.City.insert({_id:198, city:"Orly", countryRegionCode:"FR ", countryRegionName:"France", stateProvinceCode:"94 ", stateProvinceName:"Val de Marne"});
db.City.insert({_id:199, city:"Oxford", countryRegionCode:"GB ", countryRegionName:"United Kingdom", stateProvinceCode:"ENG", stateProvinceName:"England"});
db.City.insert({_id:200, city:"Oxon", countryRegionCode:"GB ", countryRegionName:"United Kingdom", stateProvinceCode:"ENG", stateProvinceName:"England"});
db.City.insert({_id:201, city:"Paderborn", countryRegionCode:"DE ", countryRegionName:"Germany", stateProvinceCode:"HH ", stateProvinceName:"Hamburg"});
db.City.insert({_id:202, city:"Paderborn", countryRegionCode:"DE ", countryRegionName:"Germany", stateProvinceCode:"NW ", stateProvinceName:"Nordrhein-Westfalen"});
db.City.insert({_id:203, city:"Palo Alto", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"CA ", stateProvinceName:"California"});
db.City.insert({_id:204, city:"Pantin", countryRegionCode:"FR ", countryRegionName:"France", stateProvinceCode:"93 ", stateProvinceName:"Seine Saint Denis"});
db.City.insert({_id:205, city:"Paris", countryRegionCode:"FR ", countryRegionName:"France", stateProvinceCode:"75 ", stateProvinceName:"Seine (Paris)"});
db.City.insert({_id:206, city:"Paris La Defense", countryRegionCode:"FR ", countryRegionName:"France", stateProvinceCode:"92 ", stateProvinceName:"Hauts de Seine"});
db.City.insert({_id:207, city:"Perth", countryRegionCode:"AU ", countryRegionName:"Australia", stateProvinceCode:"SA ", stateProvinceName:"South Australia"});
db.City.insert({_id:208, city:"Peterborough", countryRegionCode:"GB ", countryRegionName:"United Kingdom", stateProvinceCode:"ENG", stateProvinceName:"England"});
db.City.insert({_id:209, city:"Poing", countryRegionCode:"DE ", countryRegionName:"Germany", stateProvinceCode:"SL ", stateProvinceName:"Saarland"});
db.City.insert({_id:210, city:"Port Hammond", countryRegionCode:"CA ", countryRegionName:"Canada", stateProvinceCode:"BC ", stateProvinceName:"British Columbia"});
db.City.insert({_id:211, city:"Port Macquarie", countryRegionCode:"AU ", countryRegionName:"Australia", stateProvinceCode:"NSW", stateProvinceName:"New South Wales"});
db.City.insert({_id:212, city:"Port Orchard", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"WA ", stateProvinceName:"Washington"});
db.City.insert({_id:213, city:"Portland", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"OR ", stateProvinceName:"Oregon"});
db.City.insert({_id:214, city:"Puyallup", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"WA ", stateProvinceName:"Washington"});
db.City.insert({_id:215, city:"Reading", countryRegionCode:"GB ", countryRegionName:"United Kingdom", stateProvinceCode:"ENG", stateProvinceName:"England"});
db.City.insert({_id:216, city:"Redmond", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"WA ", stateProvinceName:"Washington"});
db.City.insert({_id:217, city:"Redwood City", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"CA ", stateProvinceName:"California"});
db.City.insert({_id:218, city:"Renton", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"WA ", stateProvinceName:"Washington"});
db.City.insert({_id:219, city:"Rhodes", countryRegionCode:"AU ", countryRegionName:"Australia", stateProvinceCode:"NSW", stateProvinceName:"New South Wales"});
db.City.insert({_id:220, city:"Rockhampton", countryRegionCode:"AU ", countryRegionName:"Australia", stateProvinceCode:"QLD", stateProvinceName:"Queensland"});
db.City.insert({_id:221, city:"Roissy en Brie", countryRegionCode:"FR ", countryRegionName:"France", stateProvinceCode:"77 ", stateProvinceName:"Seine et Marne"});
db.City.insert({_id:222, city:"Roncq", countryRegionCode:"FR ", countryRegionName:"France", stateProvinceCode:"59 ", stateProvinceName:"Nord"});
db.City.insert({_id:223, city:"Roubaix", countryRegionCode:"FR ", countryRegionName:"France", stateProvinceCode:"59 ", stateProvinceName:"Nord"});
db.City.insert({_id:224, city:"Royal Oak", countryRegionCode:"CA ", countryRegionName:"Canada", stateProvinceCode:"BC ", stateProvinceName:"British Columbia"});
db.City.insert({_id:225, city:"Runcorn", countryRegionCode:"GB ", countryRegionName:"United Kingdom", stateProvinceCode:"ENG", stateProvinceName:"England"});
db.City.insert({_id:226, city:"S?vres", countryRegionCode:"FR ", countryRegionName:"France", stateProvinceCode:"92 ", stateProvinceName:"Hauts de Seine"});
db.City.insert({_id:227, city:"Saarbr?cken", countryRegionCode:"DE ", countryRegionName:"Germany", stateProvinceCode:"SL ", stateProvinceName:"Saarland"});
db.City.insert({_id:228, city:"Saarlouis", countryRegionCode:"DE ", countryRegionName:"Germany", stateProvinceCode:"SL ", stateProvinceName:"Saarland"});
db.City.insert({_id:229, city:"Saint Germain en Laye", countryRegionCode:"FR ", countryRegionName:"France", stateProvinceCode:"78 ", stateProvinceName:"Yveline"});
db.City.insert({_id:230, city:"Saint Ouen", countryRegionCode:"FR ", countryRegionName:"France", stateProvinceCode:"17 ", stateProvinceName:"Charente-Maritime"});
db.City.insert({_id:231, city:"Saint Ouen", countryRegionCode:"FR ", countryRegionName:"France", stateProvinceCode:"41 ", stateProvinceName:"Loir et Cher"});
db.City.insert({_id:232, city:"Saint Ouen", countryRegionCode:"FR ", countryRegionName:"France", stateProvinceCode:"80 ", stateProvinceName:"Somme"});
db.City.insert({_id:233, city:"Saint-Denis", countryRegionCode:"FR ", countryRegionName:"France", stateProvinceCode:"93 ", stateProvinceName:"Seine Saint Denis"});
db.City.insert({_id:234, city:"Salem", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"OR ", stateProvinceName:"Oregon"});
db.City.insert({_id:235, city:"Salzgitter", countryRegionCode:"DE ", countryRegionName:"Germany", stateProvinceCode:"HE ", stateProvinceName:"Hessen"});
db.City.insert({_id:236, city:"San Carlos", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"CA ", stateProvinceName:"California"});
db.City.insert({_id:237, city:"San Diego", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"CA ", stateProvinceName:"California"});
db.City.insert({_id:238, city:"San Francisco", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"CA ", stateProvinceName:"California"});
db.City.insert({_id:239, city:"San Gabriel", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"CA ", stateProvinceName:"California"});
db.City.insert({_id:240, city:"Santa Cruz", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"CA ", stateProvinceName:"California"});
db.City.insert({_id:241, city:"Santa Monica", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"CA ", stateProvinceName:"California"});
db.City.insert({_id:242, city:"Seaford", countryRegionCode:"AU ", countryRegionName:"Australia", stateProvinceCode:"VIC", stateProvinceName:"Victoria"});
db.City.insert({_id:243, city:"Seattle", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"WA ", stateProvinceName:"Washington"});
db.City.insert({_id:244, city:"Sedro Woolley", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"WA ", stateProvinceName:"Washington"});
db.City.insert({_id:245, city:"Shawnee", countryRegionCode:"CA ", countryRegionName:"Canada", stateProvinceCode:"BC ", stateProvinceName:"British Columbia"});
db.City.insert({_id:246, city:"Silverwater", countryRegionCode:"AU ", countryRegionName:"Australia", stateProvinceCode:"NSW", stateProvinceName:"New South Wales"});
db.City.insert({_id:247, city:"Solingen", countryRegionCode:"DE ", countryRegionName:"Germany", stateProvinceCode:"NW ", stateProvinceName:"Nordrhein-Westfalen"});
db.City.insert({_id:248, city:"Sooke", countryRegionCode:"CA ", countryRegionName:"Canada", stateProvinceCode:"BC ", stateProvinceName:"British Columbia"});
db.City.insert({_id:249, city:"South Melbourne", countryRegionCode:"AU ", countryRegionName:"Australia", stateProvinceCode:"VIC", stateProvinceName:"Victoria"});
db.City.insert({_id:250, city:"Spokane", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"WA ", stateProvinceName:"Washington"});
db.City.insert({_id:251, city:"Spring Valley", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"CA ", stateProvinceName:"California"});
db.City.insert({_id:252, city:"Springwood", countryRegionCode:"AU ", countryRegionName:"Australia", stateProvinceCode:"NSW", stateProvinceName:"New South Wales"});
db.City.insert({_id:253, city:"St. Leonards", countryRegionCode:"AU ", countryRegionName:"Australia", stateProvinceCode:"NSW", stateProvinceName:"New South Wales"});
db.City.insert({_id:254, city:"Stoke-on-Trent", countryRegionCode:"GB ", countryRegionName:"United Kingdom", stateProvinceCode:"ENG", stateProvinceName:"England"});
db.City.insert({_id:255, city:"Stuttgart", countryRegionCode:"DE ", countryRegionName:"Germany", stateProvinceCode:"SL ", stateProvinceName:"Saarland"});
db.City.insert({_id:256, city:"Sulzbach Taunus", countryRegionCode:"DE ", countryRegionName:"Germany", stateProvinceCode:"SL ", stateProvinceName:"Saarland"});
db.City.insert({_id:257, city:"Sunbury", countryRegionCode:"AU ", countryRegionName:"Australia", stateProvinceCode:"VIC", stateProvinceName:"Victoria"});
db.City.insert({_id:258, city:"Suresnes", countryRegionCode:"FR ", countryRegionName:"France", stateProvinceCode:"92 ", stateProvinceName:"Hauts de Seine"});
db.City.insert({_id:259, city:"Sydney", countryRegionCode:"AU ", countryRegionName:"Australia", stateProvinceCode:"NSW", stateProvinceName:"New South Wales"});
db.City.insert({_id:260, city:"Tacoma", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"WA ", stateProvinceName:"Washington"});
db.City.insert({_id:261, city:"Torrance", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"CA ", stateProvinceName:"California"});
db.City.insert({_id:262, city:"Townsville", countryRegionCode:"AU ", countryRegionName:"Australia", stateProvinceCode:"QLD", stateProvinceName:"Queensland"});
db.City.insert({_id:263, city:"Tremblay-en-France", countryRegionCode:"FR ", countryRegionName:"France", stateProvinceCode:"93 ", stateProvinceName:"Seine Saint Denis"});
db.City.insert({_id:264, city:"Vancouver", countryRegionCode:"CA ", countryRegionName:"Canada", stateProvinceCode:"BC ", stateProvinceName:"British Columbia"});
db.City.insert({_id:265, city:"Verrieres Le Buisson", countryRegionCode:"FR ", countryRegionName:"France", stateProvinceCode:"91 ", stateProvinceName:"Essonne"});
db.City.insert({_id:266, city:"Versailles", countryRegionCode:"FR ", countryRegionName:"France", stateProvinceCode:"78 ", stateProvinceName:"Yveline"});
db.City.insert({_id:267, city:"Victoria", countryRegionCode:"CA ", countryRegionName:"Canada", stateProvinceCode:"BC ", stateProvinceName:"British Columbia"});
db.City.insert({_id:268, city:"Villeneuve-d'Ascq", countryRegionCode:"FR ", countryRegionName:"France", stateProvinceCode:"59 ", stateProvinceName:"Nord"});
db.City.insert({_id:269, city:"W. Linn", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"OR ", stateProvinceName:"Oregon"});
db.City.insert({_id:270, city:"W. York", countryRegionCode:"GB ", countryRegionName:"United Kingdom", stateProvinceCode:"ENG", stateProvinceName:"England"});
db.City.insert({_id:271, city:"Walla Walla", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"WA ", stateProvinceName:"Washington"});
db.City.insert({_id:272, city:"Warrington", countryRegionCode:"GB ", countryRegionName:"United Kingdom", stateProvinceCode:"ENG", stateProvinceName:"England"});
db.City.insert({_id:273, city:"Warrnambool", countryRegionCode:"AU ", countryRegionName:"Australia", stateProvinceCode:"VIC", stateProvinceName:"Victoria"});
db.City.insert({_id:274, city:"Watford", countryRegionCode:"GB ", countryRegionName:"United Kingdom", stateProvinceCode:"ENG", stateProvinceName:"England"});
db.City.insert({_id:275, city:"Werne", countryRegionCode:"DE ", countryRegionName:"Germany", stateProvinceCode:"NW ", stateProvinceName:"Nordrhein-Westfalen"});
db.City.insert({_id:276, city:"West Covina", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"CA ", stateProvinceName:"California"});
db.City.insert({_id:277, city:"West Sussex", countryRegionCode:"GB ", countryRegionName:"United Kingdom", stateProvinceCode:"ENG", stateProvinceName:"England"});
db.City.insert({_id:278, city:"Westminster", countryRegionCode:"CA ", countryRegionName:"Canada", stateProvinceCode:"BC ", stateProvinceName:"British Columbia"});
db.City.insert({_id:279, city:"Wokingham", countryRegionCode:"GB ", countryRegionName:"United Kingdom", stateProvinceCode:"ENG", stateProvinceName:"England"});
db.City.insert({_id:280, city:"Wollongong", countryRegionCode:"AU ", countryRegionName:"Australia", stateProvinceCode:"NSW", stateProvinceName:"New South Wales"});
db.City.insert({_id:281, city:"Woodburn", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"OR ", stateProvinceName:"Oregon"});
db.City.insert({_id:282, city:"Woodland Hills", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"CA ", stateProvinceName:"California"});
db.City.insert({_id:283, city:"Woolston", countryRegionCode:"GB ", countryRegionName:"United Kingdom", stateProvinceCode:"ENG", stateProvinceName:"England"});
db.City.insert({_id:284, city:"Yakima", countryRegionCode:"US ", countryRegionName:"United States", stateProvinceCode:"WA ", stateProvinceName:"Washington"});
db.City.insert({_id:285, city:"York", countryRegionCode:"GB ", countryRegionName:"United Kingdom", stateProvinceCode:"ENG", stateProvinceName:"England"});
