db.Currency.insert({_id:1, curCurrencyAcronymKey:"AFA", curCurrencyName:"Afghani"});
db.Currency.insert({_id:2, curCurrencyAcronymKey:"DZD", curCurrencyName:"Algerian Dinar"});
db.Currency.insert({_id:3, curCurrencyAcronymKey:"ARS", curCurrencyName:"Argentine Peso"});
db.Currency.insert({_id:4, curCurrencyAcronymKey:"AMD", curCurrencyName:"Armenian Dram"});
db.Currency.insert({_id:5, curCurrencyAcronymKey:"AWG", curCurrencyName:"Aruban Guilder"});
db.Currency.insert({_id:6, curCurrencyAcronymKey:"AUD", curCurrencyName:"Australian Dollar"});
db.Currency.insert({_id:7, curCurrencyAcronymKey:"AZM", curCurrencyName:"Azerbaijanian Manat"});
db.Currency.insert({_id:8, curCurrencyAcronymKey:"BSD", curCurrencyName:"Bahamian Dollar"});
db.Currency.insert({_id:9, curCurrencyAcronymKey:"BHD", curCurrencyName:"Bahraini Dinar"});
db.Currency.insert({_id:10, curCurrencyAcronymKey:"THB", curCurrencyName:"Baht"});
db.Currency.insert({_id:11, curCurrencyAcronymKey:"PAB", curCurrencyName:"Balboa"});
db.Currency.insert({_id:12, curCurrencyAcronymKey:"BBD", curCurrencyName:"Barbados Dollar"});
db.Currency.insert({_id:13, curCurrencyAcronymKey:"BEF", curCurrencyName:"Belgian Franc"});
db.Currency.insert({_id:14, curCurrencyAcronymKey:"VEB", curCurrencyName:"Bolivar"});
db.Currency.insert({_id:15, curCurrencyAcronymKey:"BOB", curCurrencyName:"Boliviano"});
db.Currency.insert({_id:16, curCurrencyAcronymKey:"BRL", curCurrencyName:"Brazilian Real"});
db.Currency.insert({_id:17, curCurrencyAcronymKey:"BND", curCurrencyName:"Brunei Dollar"});
db.Currency.insert({_id:18, curCurrencyAcronymKey:"BGN", curCurrencyName:"Bulgarian Lev"});
db.Currency.insert({_id:19, curCurrencyAcronymKey:"CAD", curCurrencyName:"Canadian Dollar"});
db.Currency.insert({_id:20, curCurrencyAcronymKey:"GHC", curCurrencyName:"Cedi"});
db.Currency.insert({_id:21, curCurrencyAcronymKey:"XOF", curCurrencyName:"CFA Franc BCEAO"});
db.Currency.insert({_id:22, curCurrencyAcronymKey:"CLP", curCurrencyName:"Chilean Peso"});
db.Currency.insert({_id:23, curCurrencyAcronymKey:"COP", curCurrencyName:"Colombian Peso"});
db.Currency.insert({_id:24, curCurrencyAcronymKey:"CRC", curCurrencyName:"Costa Rican Colon"});
db.Currency.insert({_id:25, curCurrencyAcronymKey:"HRK", curCurrencyName:"Croatian Kuna"});
db.Currency.insert({_id:26, curCurrencyAcronymKey:"CYP", curCurrencyName:"Cyprus Pound"});
db.Currency.insert({_id:27, curCurrencyAcronymKey:"CZK", curCurrencyName:"Czech Koruna"});
db.Currency.insert({_id:28, curCurrencyAcronymKey:"DKK", curCurrencyName:"Danish Krone"});
db.Currency.insert({_id:29, curCurrencyAcronymKey:"DEM", curCurrencyName:"Deutsche Mark"});
db.Currency.insert({_id:30, curCurrencyAcronymKey:"DOP", curCurrencyName:"Dominican Peso"});
db.Currency.insert({_id:31, curCurrencyAcronymKey:"VND", curCurrencyName:"Dong"});
db.Currency.insert({_id:32, curCurrencyAcronymKey:"GRD", curCurrencyName:"Drachma"});
db.Currency.insert({_id:33, curCurrencyAcronymKey:"EGP", curCurrencyName:"Egyptian Pound"});
db.Currency.insert({_id:34, curCurrencyAcronymKey:"SVC", curCurrencyName:"El Salvador Colon"});
db.Currency.insert({_id:35, curCurrencyAcronymKey:"AED", curCurrencyName:"Emirati Dirham"});
db.Currency.insert({_id:36, curCurrencyAcronymKey:"EUR", curCurrencyName:"EURO"});
db.Currency.insert({_id:37, curCurrencyAcronymKey:"FJD", curCurrencyName:"Fiji Dollar"});
db.Currency.insert({_id:38, curCurrencyAcronymKey:"HUF", curCurrencyName:"Forint"});
db.Currency.insert({_id:39, curCurrencyAcronymKey:"FRF", curCurrencyName:"French Franc"});
db.Currency.insert({_id:40, curCurrencyAcronymKey:"PYG", curCurrencyName:"Guarani"});
db.Currency.insert({_id:41, curCurrencyAcronymKey:"HKD", curCurrencyName:"Hong Kong Dollar"});
db.Currency.insert({_id:42, curCurrencyAcronymKey:"ISK", curCurrencyName:"Iceland Krona"});
db.Currency.insert({_id:43, curCurrencyAcronymKey:"INR", curCurrencyName:"Indian Rupee"});
db.Currency.insert({_id:44, curCurrencyAcronymKey:"IEP", curCurrencyName:"Irish Pound"});
db.Currency.insert({_id:45, curCurrencyAcronymKey:"ITL", curCurrencyName:"Italian Lira"});
db.Currency.insert({_id:46, curCurrencyAcronymKey:"JMD", curCurrencyName:"Jamaican Dollar"});
db.Currency.insert({_id:47, curCurrencyAcronymKey:"JOD", curCurrencyName:"Jordanian Dinar"});
db.Currency.insert({_id:48, curCurrencyAcronymKey:"KES", curCurrencyName:"Kenyan Shilling"});
db.Currency.insert({_id:49, curCurrencyAcronymKey:"EEK", curCurrencyName:"Kroon"});
db.Currency.insert({_id:50, curCurrencyAcronymKey:"KWD", curCurrencyName:"Kuwaiti Dinar"});
db.Currency.insert({_id:51, curCurrencyAcronymKey:"AOA", curCurrencyName:"Kwanza"});
db.Currency.insert({_id:52, curCurrencyAcronymKey:"LVL", curCurrencyName:"Latvian Lats"});
db.Currency.insert({_id:53, curCurrencyAcronymKey:"LBP", curCurrencyName:"Lebanese Pound"});
db.Currency.insert({_id:54, curCurrencyAcronymKey:"ALL", curCurrencyName:"Lek"});
db.Currency.insert({_id:55, curCurrencyAcronymKey:"ROL", curCurrencyName:"Leu"});
db.Currency.insert({_id:56, curCurrencyAcronymKey:"LTL", curCurrencyName:"Lithuanian Litas"});
db.Currency.insert({_id:57, curCurrencyAcronymKey:"MYR", curCurrencyName:"Malaysian Ringgit"});
db.Currency.insert({_id:58, curCurrencyAcronymKey:"MTL", curCurrencyName:"Maltese Lira"});
db.Currency.insert({_id:59, curCurrencyAcronymKey:"FIM", curCurrencyName:"Markka"});
db.Currency.insert({_id:60, curCurrencyAcronymKey:"MUR", curCurrencyName:"Mauritius Rupee"});
db.Currency.insert({_id:61, curCurrencyAcronymKey:"MXN", curCurrencyName:"Mexican Peso"});
db.Currency.insert({_id:62, curCurrencyAcronymKey:"MAD", curCurrencyName:"Moroccan Dirham"});
db.Currency.insert({_id:63, curCurrencyAcronymKey:"NGN", curCurrencyName:"Naira"});
db.Currency.insert({_id:64, curCurrencyAcronymKey:"NAD", curCurrencyName:"Namibia Dollar"});
db.Currency.insert({_id:65, curCurrencyAcronymKey:"NPR", curCurrencyName:"Nepalese Rupee"});
db.Currency.insert({_id:66, curCurrencyAcronymKey:"ANG", curCurrencyName:"Netherlands Antillian Guilder"});
db.Currency.insert({_id:67, curCurrencyAcronymKey:"NLG", curCurrencyName:"Netherlands Guilder"});
db.Currency.insert({_id:68, curCurrencyAcronymKey:"ILS", curCurrencyName:"New Israeli Shekel"});
db.Currency.insert({_id:69, curCurrencyAcronymKey:"TWD", curCurrencyName:"New Taiwan Dollar"});
db.Currency.insert({_id:70, curCurrencyAcronymKey:"NZD", curCurrencyName:"New Zealand Dollar"});
db.Currency.insert({_id:71, curCurrencyAcronymKey:"BTN", curCurrencyName:"Ngultrum"});
db.Currency.insert({_id:72, curCurrencyAcronymKey:"NOK", curCurrencyName:"Norwegian Krone"});
db.Currency.insert({_id:73, curCurrencyAcronymKey:"PEN", curCurrencyName:"Nuevo Sol"});
db.Currency.insert({_id:74, curCurrencyAcronymKey:"OMR", curCurrencyName:"Omani Rial"});
db.Currency.insert({_id:75, curCurrencyAcronymKey:"PKR", curCurrencyName:"Pakistan Rupee"});
db.Currency.insert({_id:76, curCurrencyAcronymKey:"PHP", curCurrencyName:"Philippine Peso"});
db.Currency.insert({_id:77, curCurrencyAcronymKey:"PLZ", curCurrencyName:"Polish Zloty(old)"});
db.Currency.insert({_id:78, curCurrencyAcronymKey:"PTE", curCurrencyName:"Portuguese Escudo"});
db.Currency.insert({_id:79, curCurrencyAcronymKey:"GTQ", curCurrencyName:"Quetzal"});
db.Currency.insert({_id:80, curCurrencyAcronymKey:"ZAR", curCurrencyName:"Rand"});
db.Currency.insert({_id:81, curCurrencyAcronymKey:"MVR", curCurrencyName:"Rufiyaa"});
db.Currency.insert({_id:82, curCurrencyAcronymKey:"IDR", curCurrencyName:"Rupiah"});
db.Currency.insert({_id:83, curCurrencyAcronymKey:"RUB", curCurrencyName:"Russian Ruble"});
db.Currency.insert({_id:84, curCurrencyAcronymKey:"RUR", curCurrencyName:"Russian Ruble(old)"});
db.Currency.insert({_id:85, curCurrencyAcronymKey:"SAR", curCurrencyName:"Saudi Riyal"});
db.Currency.insert({_id:86, curCurrencyAcronymKey:"ATS", curCurrencyName:"Shilling"});
db.Currency.insert({_id:87, curCurrencyAcronymKey:"SGD", curCurrencyName:"Singapore Dollar"});
db.Currency.insert({_id:88, curCurrencyAcronymKey:"SKK", curCurrencyName:"Slovak Koruna"});
db.Currency.insert({_id:89, curCurrencyAcronymKey:"ESP", curCurrencyName:"Spanish Peseta"});
db.Currency.insert({_id:90, curCurrencyAcronymKey:"LKR", curCurrencyName:"Sri Lankan Rupee"});
db.Currency.insert({_id:91, curCurrencyAcronymKey:"SEK", curCurrencyName:"Swedish Krona"});
db.Currency.insert({_id:92, curCurrencyAcronymKey:"CHF", curCurrencyName:"Swiss Franc"});
db.Currency.insert({_id:93, curCurrencyAcronymKey:"BDT", curCurrencyName:"Taka"});
db.Currency.insert({_id:94, curCurrencyAcronymKey:"SIT", curCurrencyName:"Tolar"});
db.Currency.insert({_id:95, curCurrencyAcronymKey:"TTD", curCurrencyName:"Trinidad and Tobago Dollar"});
db.Currency.insert({_id:96, curCurrencyAcronymKey:"TND", curCurrencyName:"Tunisian Dinar"});
db.Currency.insert({_id:97, curCurrencyAcronymKey:"TRL", curCurrencyName:"Turkish Lira"});
db.Currency.insert({_id:98, curCurrencyAcronymKey:"GBP", curCurrencyName:"United Kingdom Pound"});
db.Currency.insert({_id:99, curCurrencyAcronymKey:"UYU", curCurrencyName:"Uruguayan Peso"});
db.Currency.insert({_id:100, curCurrencyAcronymKey:"USD", curCurrencyName:"US Dollar"});
db.Currency.insert({_id:101, curCurrencyAcronymKey:"KRW", curCurrencyName:"Won"});
db.Currency.insert({_id:102, curCurrencyAcronymKey:"JPY", curCurrencyName:"Yen"});
db.Currency.insert({_id:103, curCurrencyAcronymKey:"CNY", curCurrencyName:"Yuan Renminbi"});
db.Currency.insert({_id:104, curCurrencyAcronymKey:"ZWD", curCurrencyName:"Zimbabwe Dollar"});
db.Currency.insert({_id:105, curCurrencyAcronymKey:"PLN", curCurrencyName:"Zloty"});
